import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const API=import.meta.env.VITE_API_URL||'http://localhost:5000/api';
const demo=[{id:'demo1',name:'Goa Trip 2026',description:"Four days we'll never forget.",members:6,memories:128},{id:'demo2',name:'College Farewell',description:'The last day, the best stories.',members:32,memories:74},{id:'demo3',name:"Dhwani's Birthday",description:'A day full of little surprises.',members:8,memories:46}];

async function api(path,opts={}){const token=localStorage.getItem('memora_token');const r=await fetch(API+path,{...opts,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...(opts.headers||{})}});const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed');return data}

function App(){
 const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem('memora_user')||'null'));
 const [page,setPage]=useState('home'); const [albums,setAlbums]=useState(demo); const [selected,setSelected]=useState(null); const [modal,setModal]=useState(null); const [msg,setMsg]=useState('');
 useEffect(()=>{if(user)api('/albums').then(setAlbums).catch(()=>{});},[user]);
 const notify=x=>{setMsg(x);setTimeout(()=>setMsg(''),2200)};
 async function login(e){e.preventDefault();try{const d=await api('/auth/login',{method:'POST',body:JSON.stringify({email:e.target.email.value,password:e.target.password.value})});localStorage.setItem('memora_token',d.token);localStorage.setItem('memora_user',JSON.stringify(d.user));setUser(d.user);notify('Welcome back ✨')}catch(x){notify(x.message)}}
 async function createAlbum(e){e.preventDefault();try{const d=await api('/albums',{method:'POST',body:JSON.stringify({name:e.target.name.value,description:e.target.description.value,location:e.target.location.value})});setAlbums(a=>[d,...a]);setModal(null);notify('Private album created 🔒')}catch(x){notify(x.message)}}
 if(!user)return <Auth login={login}/>;
 return <div><header><b>Memora<span>.</span></b><nav><button className={page==='home'?'on':''} onClick={()=>setPage('home')}>Home</button><button className={page==='albums'?'on':''} onClick={()=>setPage('albums')}>Albums</button><button className={page==='memories'?'on':''} onClick={()=>setPage('memories')}>Memories</button></nav><button className="avatar" onClick={()=>{localStorage.clear();setUser(null)}}>{user.name?.[0]?.toUpperCase()}</button></header>
 <main>
 {page==='home'&&<><div className="hero"><div><small>YOUR PRIVATE MEMORY SPACE</small><h1>Keep the moments.<br/>Relive them together.</h1><p>Photos become stories when the people who lived them are here.</p></div><button className="primary" onClick={()=>setModal('album')}>＋ Create album</button></div><section className="onthis"><div><small>ON THIS DAY</small><h2>3 years ago, you were in Manali ❤️</h2><p>27 memories • 5 people • one unforgettable weekend</p></div><button onClick={()=>notify('Memory playback coming next ✨')}>Relive this →</button></section><Section title="Your albums" action={()=>setPage('albums')}/><div className="grid">{albums.slice(0,3).map(a=><Album a={a} key={a.id} open={()=>setSelected(a)}/>)}</div></>}
 {page==='albums'&&<><div className="hero"><div><small>PRIVATE CIRCLES</small><h1>Your albums</h1><p>Only invited people can see what's inside.</p></div><button className="primary" onClick={()=>setModal('album')}>＋ Create album</button></div><div className="grid">{albums.map(a=><Album a={a} key={a.id} open={()=>setSelected(a)}/>)}</div></>}
 {page==='memories'&&<><div className="hero"><div><small>YOUR TIMELINE</small><h1>All memories</h1><p>Every little moment your circles chose to keep.</p></div></div><MemoryList selected={selected}/></>}
 {selected&&<AlbumView a={selected} close={()=>setSelected(null)} notify={notify}/>}
 </main>{modal==='album'&&<Modal title="Create a memory album" close={()=>setModal(null)}><form onSubmit={createAlbum}><label>Album name<input name="name" required placeholder="Goa Trip 2026"/></label><label>Description<textarea name="description" placeholder="What made this gathering special?"/></label><label>Location<input name="location" placeholder="Goa, India"/></label><button className="primary">Create album</button></form></Modal>}{msg&&<div className="toast">{msg}</div>}</div>
}

function Auth({login}){return <div className="auth"><div className="authbox"><b className="brand">Memora<span>.</span></b><small>PRIVATE MEMORIES, TOGETHER.</small><h1>Welcome back.</h1><p>Sign in to your memory circles.</p><form onSubmit={login}><input name="email" type="email" required placeholder="Email"/><input name="password" type="password" required placeholder="Password"/><button className="primary">Sign in</button></form><p className="hint">Create a user directly with the API endpoint <code>POST /api/auth/register</code>.</p></div></div>}
const Section=({title,action})=><div className="section"><h2>{title}</h2><button onClick={action}>View all →</button></div>;
function Album({a,open}){return <article className="album" onClick={open}><div className="cover"><i>🔒 Private</i></div><div className="body"><h3>{a.name}</h3><p>{a.description}</p><small>{a.memories||0} memories • {a.members||1} people</small></div></article>}
function MemoryList(){return <div className="memories"><article className="memory"><div className="photo p1"/><div><small>GOA TRIP 2026 • KELVIN • YESTERDAY</small><h2>The sunset we almost missed.</h2><p>We were late because everyone took forever to get ready. Somehow we still reached the beach just before the sun disappeared.</p><span>🎙️ 0:24 Voice memory</span><span>🎵 Iktara</span><span>♡ 8</span></div></article><article className="memory"><div className="photo p2"/><div><small>COLLEGE FAREWELL • JAY • 4 DAYS AGO</small><h2>One last photo before everyone left.</h2><p>None of us wanted to say goodbye, so we kept taking “one final picture” until it got dark.</p><span>💬 12</span><span>♡ 21</span></div></article></div>}
function AlbumView({a,close,notify}){const [mems,setMems]=useState([]);const [title,setTitle]=useState('');const [story,setStory]=useState('');useEffect(()=>{if(!String(a.id).startsWith('demo'))api('/albums/'+a.id+'/memories').then(setMems).catch(()=>{})},[a]);async function save(e){e.preventDefault();try{const m=await api('/albums/'+a.id+'/memories',{method:'POST',body:JSON.stringify({title,story})});setMems(x=>[m,...x]);setTitle('');setStory('');notify('Memory saved ✨')}catch(x){notify(x.message)}}return <div className="drawer"><div className="drawerhead"><button onClick={close}>← Back</button><button onClick={close}>×</button></div><small>🔒 PRIVATE ALBUM</small><h1>{a.name}</h1><p>{a.description}</p><div className="onthis"><div><small>SHARED SPACE</small><h2>Everyone's version of the day.</h2><p>Write a story now; media storage can be connected to the same memory later.</p></div></div><form className="memoryform" onSubmit={save}><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Memory title"/><textarea value={story} onChange={e=>setStory(e.target.value)} placeholder="What happened? What do you want everyone to remember?"/><button className="primary">＋ Save memory</button></form>{mems.map(m=><article className="textmemory" key={m.id}><small>{new Date(m.memory_date).toLocaleString()} • {m.author||'You'}</small><h2>{m.title}</h2><p>{m.story}</p></article>)}</div>}
function Modal({title,close,children}){return <div className="modal"><div className="modalbox"><div className="modalhead"><h2>{title}</h2><button onClick={close}>×</button></div>{children}</div></div>}

createRoot(document.getElementById('root')).render(<App/>);
